eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: school

  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: Neterusama123
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

